### ISSUE TITLE
Unsafe HTML being displayed escaped under Slim

### ISSUE THREAD

**Issue by jshirley** [ShPakvel/simple_navigation_renderers#3]
Hi there,

Love the renderer you built, but I ran into one small problem with it. I'm using Slim in my application, and the Caret dropdowns were escaped, showing menu items like "Users <b class="caret"></b>" rather than the actual caret.

I put in a very quick fix in my fork, but I don't like relying on something like respond_to? for this and figured you may have a better understanding for the better way of doing this:
https://github.com/jshirley/simple_navigation_renderers/commit/b21a3ae8082b51e7f53c83d65bd4027d437e6639

My knowledge of other Ruby frameworks is pretty limited, but this simple change worked for me.

Thanks for your great module!

-Jay

**Comment by ShPakvel** [comment]
Hi, Jay.

I am glad somebody likes my work.
Of course I will check your issue. I think at this weekend I will find some time to look closer at it.
And thanks for your interest.

/Pavel

**Comment by ShPakvel** [comment]
Hi, Jay.

Your approach to solve the problem is correct. The same is used in [`simple_navigation`](https://github.com/codeplant/simple-navigation) gem.
But [`simple_navigation`](https://github.com/codeplant/simple-navigation) has changed default behaviour for link titles recently. See [3.13.0](https://github.com/codeplant/simple-navigation/blob/master/CHANGELOG.md#3130).
What version of `simple_navigation` gem do you use?
If it is your problem then change the [`consider_item_names_as_safe`](https://github.com/codeplant/simple-navigation/blob/master/generators/navigation_config/templates/config/navigation.rb#L34-L35) parameter to `true` in your configuration file.
If it is not the case let me know and I will investigate it deeper.

BTW, soon I will add new renderers for Bootstrap `breadcrumb` navigation. Now it is created in separate [branch](https://github.com/ShPakvel/simple_navigation_renderers/tree/bootstrap_breadcrumbs). Maybe it will be interested for you. ;)

/Pavel

**Comment by jshirley** [comment]
Breadcrumbs will be neat to see! In my fork I have a simple thing which is working for me, which you may have seen :)

Ah, I missed the configuration option for consider_item_names_as_safe, thank you for pointing that out.

Thank you very much,
-Jay
